name: Master & Snapshot

on:
  push:
    branches:
      - "master"

jobs:
  build-and-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.3.1577'
          bb: 'latest'
      - name: Cache All The Things
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
            ~/.deps.clj
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn', '**/bb.edn') }}
      - name: Run All Tests, then Build & Deploy Snapshot
        run: bb ci:deploy snapshot jdk21
        env:
          CLOJARS_PASSWORD: ${{secrets.DEPLOY_TOKEN}}
          CLOJARS_USERNAME: ${{secrets.DEPLOY_USERNAME}}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.3.1577'
          bb: 'latest'
      - name: Cache All The Things
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.clojure
            ~/.cpcache
            ~/.deps.clj
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn', '**/bb.edn') }}
      - name: Run Tests
        run: bb test jdk${{ matrix.java }}
